### ISSUE TITLE
update gadget-mocks.js to allow for e2e testing on widget page

### ISSUE THREAD

**Issue by nexus-uw** [Rise-Vision/widget-tester#35]
it would need to support the following RPCs
- `rsevent_ready`
- `rsparam_get`

rpc.register would also need to be updated to allow for proper registration of callbacks as well

**Comment by alanclayton** [comment]
@donnapep @stulees can this be closed?

**Comment by donnapep** [comment]
@alanclayton Yup, this is already implemented.
